"""empty message

Revision ID: 880ca555faa5
Revises: 4fd5c8b52471
Create Date: 2019-06-06 12:47:29.372477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880ca555faa5'
down_revision = '4fd5c8b52471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
